# Generated by Django 3.2.7 on 2021-09-15 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditcard',
            options={'verbose_name': 'Cartão de Crédito', 'verbose_name_plural': 'Cartões de Crédito'},
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='invoice_close_day',
            field=models.IntegerField(verbose_name='Dia de fechamento da Fatura'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateTimeField(verbose_name='Data')),
                ('value', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Valor')),
                ('is_service', models.BooleanField(default=False, verbose_name='É um serviço?')),
                ('is_installment', models.BooleanField(default=False, verbose_name='É parcelado?')),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('has_promotion', models.BooleanField(default=False, verbose_name='Tem promoção?')),
                ('promotion_num_months', models.SmallIntegerField(default=0, verbose_name='Número de mêses com a promoção')),
                ('credit_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.creditcard', verbose_name='Cartão de Crédito')),
            ],
        ),
        migrations.AddConstraint(
            model_name='bill',
            constraint=models.CheckConstraint(check=models.Q(('is_service', True), ('is_installment', True), _negated=True), name='service_and_installment_not_both_true'),
        ),
    ]
