# Generated by Django 3.2.7 on 2021-09-15 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210915_1906'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'verbose_name': 'Conta', 'verbose_name_plural': 'Contas'},
        ),
        migrations.RemoveConstraint(
            model_name='bill',
            name='service_and_installment_not_both_true',
        ),
        migrations.RenameField(
            model_name='bill',
            old_name='promotion_num_months',
            new_name='promotion_count',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='end_date',
        ),
        migrations.AddField(
            model_name='bill',
            name='end_service_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de finalização do Serviço'),
        ),
        migrations.AddField(
            model_name='bill',
            name='installment_count',
            field=models.SmallIntegerField(default=0, verbose_name='Número de parcelas'),
        ),
        migrations.AddConstraint(
            model_name='bill',
            constraint=models.CheckConstraint(check=models.Q(('is_service', True), ('is_installment', True), _negated=True), name="Service and Installmente can't both be True."),
        ),
    ]
