# Generated by Django 3.0.7 on 2020-06-29 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditcard',
            old_name='invoce_date',
            new_name='invoice_date',
        ),
    ]
